#!/bin/zsh

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
    git
    zsh-autosuggestions
    zsh_reload
    history
)

# Auto Update OMZ
DISABLE_UPDATE_PROMPT=true

source $ZSH/oh-my-zsh.sh

/usr/bin/sh /etc/motd.sh

HISTSIZE=1000000
SAVEHIST=1000000

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line

source ~/.dotfiles/zsh_aliases

export VISUAL=vim
export EDITOR="$VISUAL"
export GPG_TTY=$(tty)
